color: true
dry-run: null
hookfiles: ./Provider/test/DreddHooks.js
language: nodejs
require: null
server: null
server-wait: null
init: false
custom: {}
names: false
only: []
reporter: [markdown]
# reporter: apiary
output: [./Provider/results/ExecutionReport.md]
header: []
sorted: false
user: null
inline-errors: true
details: true
method: []
loglevel: debug
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: .Provider/dredd.yml
path: []

endpoint: 'http://localhost:8080'
blueprint: ./Provider/oas/EmployeeApi_V1.yaml