name: Build

# on:
#   push:
#   workflow_dispatch:
#   schedule:
#     - cron:  '* * * * *'    # At every 15th minute




on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://epam7.pactflow.io
  PACT_BROKER_TOKEN: GNkMi3cglj-TvEuf73-0TA
  # PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  BASE_URL: https://epam7.pactflow.io
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  Generate-Consumer-Contracts:
    runs-on: windows-latest
    strategy:
      matrix:
        pact_provider:
          ["get-employee-api-provider"]
    steps:
      - name: Checkout Consumer Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16.15.1'

      - name: Installing All The Packages
        run: npm install --f

      - name: Downloading PACT Ruby Standalone
        run: curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-win32.zip
      
      - name: Unzipping PACT Ruby Standalone      
        run: Powershell Expand-Archive pact-1.91.0-win32.zip

      - name: Executing Tests For ${{ matrix.pact_provider }}
        run: npm run consumerTest
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}

      - name: Publish Pacts For ${{ matrix.pact_consumer }} & ${{ github.ref }}
        run: npm run publish:consumerA
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}

#   Can-I-Deploy-Consumer:
#     runs-on: windows-latest
# #     needs: Generate-Consumer-Contracts
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2-beta
#       - name: Checking Availability Of Provider Contract In Pactflow
#         run: curl -X GET https://epam7.pactflow.io/pacts/provider/get-employee-api-provider -H "Authorization: Bearer GNkMi3cglj-TvEuf73-0TA" -H "Content-Type: application/json"

#   # Runs on branches as well, so we know the status of our PRs
#   Can-I-Deploy-Consumer:
#     runs-on: windows-latest
#     needs: Generate-Consumer-Contracts
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2-beta
#         with:
#           node-version: '16.15.1'
#       - name: Installing All The Packages For ${{ matrix.pact_provider }}
#         run: npm install --f

#       - name: Downloading & Unzipping PACT Ruby Standalone On Windows Machine
#       - run: curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-win32.zip
#       - run: Powershell Expand-Archive pact-1.91.0-win32.zip

#       - name: Executing "Can I deploy?" Command For Consumer
#         run: npm run can-i-deploy-consumer
